const { cmd } = require("../command.cjs");
const axios = require("axios");
const yts = require("yt-search");
const config = require("../config.cjs");

cmd({
    pattern: "song",
    alias: ["yta", "mp3", "play"],
    react: "🎧",
    desc: "Download YouTube MP3 with buttons",
    category: "download",
    filename: __filename,
}, async (bot, mek, m, { from, q, reply, prefix }) => {
    try {
        if (!q) return reply("🎧 *QUEEN-NILU-MD SONG SEARCH*\n\nExample: .song alone");

        const search = await yts(q);
        const video = search.videos[0];
        if (!video) return reply("❌ No results found on YouTube.");

        const id = Date.now(); // unique id

        let msg = `🎵 *ZANTA AUDIO PLAYER* 🎵\n\n` +
                  `📝 *Title:* ${video.title}\n` +
                  `👤 *Artist:* ${video.author.name}\n` +
                  `⏱️ *Duration:* ${video.timestamp}\n\n` +
                  `🔘 *Select format below*`;

        const sentMsg = await bot.sendMessage(from, {
            image: { url: video.thumbnail },
            caption: msg,
            footer: "© QUEEN-NILU-MD SONG SERVICE",
            buttons: [
                {
                    buttonId: `song_audio_${id}`,
                    buttonText: { displayText: "🎧 Audio" },
                    type: 1
                },
                {
                    buttonId: `song_doc_${id}`,
                    buttonText: { displayText: "📄 Document" },
                    type: 1
                }
            ],
            headerType: 4
        }, { quoted: mek });

        // --- Listener ---
        const listener = async (update) => {
            const msgUpdate = update.messages[0];
            if (!msgUpdate.message) return;

            const buttonId = msgUpdate.message?.buttonsResponseMessage?.selectedButtonId;

            if (!buttonId) return;

            // Check if it's response to this message
            const isReplyToBot =
                msgUpdate.message.buttonsResponseMessage?.contextInfo?.stanzaId === sentMsg.key.id;

            if (isReplyToBot && buttonId.includes(id)) {
                await bot.sendMessage(from, { react: { text: '⏳', key: msgUpdate.key } });

                try {
                    const finalLink = await getDownloadLink(video.url);
                    if (!finalLink) return reply("❌ Download link not found.");

                    if (buttonId.startsWith("song_audio_")) {
                        await bot.sendMessage(from, {
                            audio: { url: finalLink },
                            mimetype: "audio/mpeg",
                            ptt: false
                        }, { quoted: msgUpdate });

                    } else if (buttonId.startsWith("song_doc_")) {
                        await bot.sendMessage(from, {
                            document: { url: finalLink },
                            mimetype: "audio/mpeg",
                            fileName: `${video.title}.mp3`,
                            caption: "> *© Generated by QUEEN-NILU-MD*"
                        }, { quoted: msgUpdate });
                    }

                    await bot.sendMessage(from, { react: { text: '✅', key: msgUpdate.key } });

                } catch (err) {
                    console.error(err);
                    reply("❌ Error downloading audio.");
                }

                bot.ev.off('messages.upsert', listener);
            }
        };

        bot.ev.on('messages.upsert', listener);

        setTimeout(() => {
            bot.ev.off('messages.upsert', listener);
        }, 300000);

    } catch (e) {
        console.log("SONG ERROR:", e);
        reply("❌ *Error:* " + e.message);
    }
});

// --- API Logic ---
async function getDownloadLink(videoUrl) {
    try {
        const apiUrl = `https://api-site-x-by-manul.vercel.app/convert?mp3=${encodeURIComponent(videoUrl)}&apikey=Manul-Official`;
        const response = await axios.get(apiUrl);
        if (response.data?.status && response.data.data?.url) return response.data.data.url;

        const backupUrl = `https://api.giftedtech.my.id/api/download/dlmp3?url=${encodeURIComponent(videoUrl)}&apikey=gifted`;
        const backup = await axios.get(backupUrl);
        return backup.data.result?.download_url;
    } catch (e) {
        return null;
    }
}
